# Copyright 2023 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Mapping extensions to MIME types."""

visibility(["//third_party/utp/starlib/launcher/..."])

MIME_TYPES = {
    "3g2": "video/3gpp2",
    "3gp": "video/3gpp",
    "3gpp": "video/3gpp",
    "DEBUG": "text/plain",
    "ERROR": "text/plain",
    "FATAL": "text/plain",
    "INFO": "text/plain",
    "SEVERE": "text/plain",
    "STDERR": "text/plain",
    "STDOUT": "text/plain",
    "WARNING": "text/plain",
    "ai": "application/illustrator",
    "aif": "audio/x-aiff",
    "aifc": "audio/x-aiff",
    "aiff": "audio/x-aiff",
    "apk": "application/vnd.android.package-archive",
    "appcache": "text/cache-manifest",  # HTML5
    "as": "text/x-actionscript",
    "asc": "text/plain",
    "ascii": "text/plain",
    "ascii_proto": "text/x-text-proto",
    "asciipb": "text/x-text-proto",
    "asciiproto": "text/x-text-proto",
    "asf": "video/x-ms-asf",
    "asx": "video/x-ms-asf",
    "au": "audio/basic",
    "avi": "video/x-msvideo",
    "bcl": "text/x-bcl",
    "bcpio": "application/x-bcpio",
    "bin": "application/octet-stream",
    "blueprint": "text/x-ncl",
    "bmp": "image/bmp",
    "borg": "text/x-bcl",
    "bz2": "application/x-bzip2",
    "c": "text/x-csrc",
    "cab": "application/octet-stream",
    "cc": "text/x-c++src",
    "cdf": "application/x-netcdf",
    "class": "application/octet-stream",
    "cod": "application/vnd.rim.cod",  # Blackberry RIM
    "cpio": "application/x-cpio",
    "cpp": "text/x-c++src",
    "cpt": "application/mac-compactpro",
    "crash": "text/plain",
    "crx": "application/x-chrome-extension",
    "csh": "application/x-csh",
    "css": "text/css",
    "csv": "text/csv",
    "dart": "application/dart",
    "dcr": "application/x-director",
    "deb": "application/x-debian-package",
    "diff": "text/plain",
    "dir": "application/x-director",
    "dll": "application/octet-stream",
    "dmg": "application/octet-stream",
    "dms": "application/octet-stream",
    "doc": "application/msword",
    "docm": "application/vnd.ms-word.document.macroEnabled.12",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "dot": "application/msword",
    "dotm": "application/vnd.ms-word.template.macroEnabled.12",
    "dotx": "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "dvi": "application/x-dvi",
    "dxf": "application/dxf",  # Data Exchange Format - Autodesk AutoCad
    "dxr": "application/x-director",
    "el": "text/x-common-lisp",
    "eml": "text/plain",
    "eps": "application/postscript",
    "epub": "application/epub+zip",
    "err": "text/plain",
    "etx": "text/x-setext",
    "exe": "application/octet-stream",
    "flv": "video/x-flv",
    "fnt": "application/octet-stream+fnt",  # Older windows font types
    "fon": "application/octet-stream+fon",  # Older windows font types
    "gcl": "text/x-gcl",
    "gg": "application/zip",
    "gif": "image/gif",
    "go": "text/x-go",
    "gpx": "application/gpx+xml",  # GPS Exchange Format
    "gtar": "application/x-gtar",
    "gz": "application/x-gzip",
    "h": "text/x-chdr",
    "hdf": "application/x-hdf",
    "hpp": "text/x-c++hdr",
    "hqx": "application/mac-binhex40",
    "hsc": "text/x-haskell",
    "htm": "text/html",
    "html": "text/html",
    "hwl": "application/HttpWatchStudio.Document",  # See http://filext.com/file-extension/HWL
    "ice": "x-conference/x-cooltalk",
    "ico": "image/x-icon",
    "ief": "image/ief",
    "iges": "model/iges",
    "igs": "model/iges",
    "inc": "text/plain",
    "jad": "text/vnd.sun.j2me.app-descriptor",  # generic J2ME
    "jar": "application/java-archive",
    "java": "text/x-java",
    "jnlp": "application/x-java-jnlp-file",
    "jpe": "image/jpeg",
    "jpeg": "image/jpeg",
    "jpg": "image/jpeg",
    "js": "application/x-javascript",
    "json": "application/json",
    "kar": "audio/midi",
    "kml": "application/vnd.google-earth.kml+xml",
    "kmz": "application/vnd.google-earth.kmz",
    "latex": "application/x-latex",
    "lcov": "text/plain",
    "lha": "application/octet-stream",
    "lisp": "text/x-common-lisp",
    "log": "text/plain",
    "lsp": "text/x-common-lisp",
    "lzh": "application/octet-stream",
    "m": "text/x-objectivec",
    "m2v": "video/mpeg",
    "m4v": "video/x-m4v",
    "man": "application/x-troff-man",
    "markdown": "text/x-markdown",
    "md": "text/x-markdown",
    "mdown": "text/x-markdown",
    "me": "application/x-troff-me",
    "mesh": "model/mesh",
    "mid": "audio/midi",
    "midi": "audio/midi",
    "mif": "application/vnd.mif",
    "mkd": "text/x-markdown",
    "mkdn": "text/x-markdown",
    "mlir": "text/x-mlir",
    "mm": "text/x-objectivec++",
    "mov": "video/quicktime",
    "movie": "video/x-sgi-movie",
    "mp2": "audio/mpeg",
    "mp3": "audio/mpeg",
    "mp4": "video/mp4",
    "mpe": "video/mpeg",
    "mpeg": "video/mpeg",
    "mpg": "video/mpeg",
    "mpga": "audio/mpeg",
    "ms": "application/x-troff-ms",
    "msh": "model/mesh",
    "msi": "application/octet-stream",
    "nc": "application/x-netcdf",
    "ncl": "text/x-ncl",
    "odc": "application/vnd.oasis.opendocument.chart",
    "odf": "application/vnd.oasis.opendocument.formula",
    "odg": "application/vnd.oasis.opendocument.graphics",
    "odi": "application/vnd.oasis.opendocument.image",
    "odm": "application/vnd.oasis.opendocument.text-master",
    "odp": "application/vnd.oasis.opendocument.presentation",
    "ods": "application/vnd.oasis.opendocument.spreadsheet",
    "odt": "application/vnd.oasis.opendocument.text",
    "ogv": "video/ogg",
    "opf": "application/oebps-package+xml",
    "otc": "application/vnd.oasis.opendocument.chart-template",
    "otf": "application/vnd.oasis.opendocument.formula-template",
    "otg": "application/vnd.oasis.opendocument.graphics-template",
    "oth": "application/vnd.oasis.opendocument.text-web",
    "oti": "application/vnd.oasis.opendocument.image-template",
    "otp": "application/vnd.oasis.opendocument.presentation-template",
    "ots": "application/vnd.oasis.opendocument.spreadsheet-template",
    "ott": "application/vnd.oasis.opendocument.text-template",
    "out": "text/plain",
    "pages": "application/x-iwork-pages-sffpages",  # Mac iWork pages
    "pb": "text/x-text-proto",
    "pb_ascii": "text/x-text-proto",
    "pb_text": "text/x-text-proto",
    "pba": "text/x-text-proto",
    "pbascii": "text/x-text-proto",
    "pbm": "image/x-portable-bitmap",
    "pbtext": "text/x-text-proto",
    "pbtxt": "text/x-text-proto",
    "pcap": "application/vnd.tcpdump.pcap",
    "pdb": "chemical/x-pdb",
    "pdf": "application/pdf",
    "pgm": "image/x-portable-graymap",
    "pgn": "application/x-chess-pgn",
    "php": "application/x-httpd-php",
    "pi": "text/x-python",  # Piccolo files
    "pkg": "application/octet-stream",
    "pkpass": "application/vnd-com.apple.pkpass",  # iOS 6 Passbook
    "png": "image/png",
    "pnm": "image/x-portable-anymap",
    "pot": "application/vnd.ms-powerpoint",
    "potm": "application/vnd.ms-powerpoint.template.macroEnabled.12",
    "potx": "application/vnd.openxmlformats-officedocument.presentationml.template",
    "ppm": "image/x-portable-pixmap",
    "pps": "application/vnd.ms-powerpoint",
    "ppsm": "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
    "ppsx": "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    "ppt": "application/vnd.ms-powerpoint",
    "pptm": "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "prc": "application/vnd.palm",  # See http://www.iana.org/assignments/media-types/application/vnd.palm
    "proto": "text/x-text-proto",
    "ps": "application/postscript",
    "psd": "application/photoshop",
    "py": "text/x-python",
    "qt": "video/quicktime",
    "ra": "audio/x-realaudio",
    "ram": "audio/x-pn-realaudio",
    "rar": "application/rar",
    "ras": "image/x-cmu-raster",
    "rdf": "text/xml",
    "recordio": "application/octet-stream",
    "rgb": "image/x-rgb",
    "rm": "audio/x-pn-realaudio",
    "roff": "application/x-troff",
    "rpm": "application/x-rpm",
    "rtf": "application/rtf",
    "rtx": "text/richtext",
    "sdc": "application/vnd.stardivision.calc",
    "sdd": "application/vnd.stardivision.impress",
    "sdw": "application/vnd.stardivision.writer",
    "sgm": "text/sgml",
    "sgml": "text/sgml",
    "sh": "application/x-sh",
    "shar": "application/x-shar",
    "silo": "model/mesh",
    "sis": "application/vnd.symbian.install",
    "sit": "application/x-stuffit",
    "skd": "application/x-koan",
    "skm": "application/x-koan",
    "skp": "application/x-koan",
    "skt": "application/x-koan",
    "sldx": "application/vnd.openxmlformats-officedocument.presentationml.slide",
    "smi": "application/smil",
    "smil": "application/smil",
    "snd": "audio/basic",
    "spl": "application/x-futuresplash",
    "splitlogs": "application/octet-stream",
    "sql": "application/sql",
    "src": "application/x-wais-source",
    "stderr": "text/plain",
    "stdout": "text/plain",
    "sv4cpio": "application/x-sv4cpio",
    "sv4crc": "application/x-sv4crc",
    "svg": "image/svg+xml",
    "swf": "application/x-shockwave-flash",
    "sxc": "application/vnd.sun.xml.calc",
    "sxi": "application/vnd.sun.xml.impress",
    "sxw": "application/vnd.sun.xml.writer",
    "szl": "text/plain",
    "t": "application/x-troff",
    "tar": "application/x-tar",
    "tcl": "application/x-tcl",
    "tex": "application/x-tex",
    "texi": "application/x-texinfo",
    "texinfo": "application/x-texinfo",
    "text_proto": "text/x-text-proto",
    "textpb": "text/x-text-proto",
    "textproto": "text/x-text-proto",
    "tgz": "application/x-gzip",
    "tif": "image/tiff",
    "tiff": "image/tiff",
    "tr": "application/x-troff",
    "tsv": "text/tab-separated-values",
    "ttf": "application/x-font-ttf",  # appears to be more popular than application/x-font-truetype
    "txt": "text/plain",
    "txtpb": "text/x-text-proto",
    "ustar": "application/x-ustar",
    "vcd": "application/x-cdlink",
    "vcf": "text/x-vcard",
    "vrml": "model/vrml",
    "wav": "audio/x-wav",
    "wax": "audio/x-ms-wax",
    "webm": "video/webm",
    "webp": "image/webp",
    "wm": "video/x-ms-wm",
    "wma": "audio/x-ms-wma",
    "wmf": "image/x-wmf",
    "wml": "text/vnd.wap.wml",
    "wmv": "video/x-ms-wmv",
    "woff": "application/x-font-woff",  # Web Open Font Format
    "wpd": "application/wordperfect",  # See http://filext.com/file-extension/WPD
    "wrl": "model/vrml",
    "wsdl": "text/xml",
    "wvx": "video/x-ms-wvx",
    "xbm": "image/x-xbitmap",
    "xhtml": "application/xhtml+xml",
    "xls": "application/vnd.ms-excel",
    "xlsm": "application/vnd.ms-excel.sheet.macroEnabled.12",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "xlt": "application/vnd.ms-excel",
    "xltm": "application/vnd.ms-excel.template.macroEnabled.12",
    "xltx": "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    "xml": "text/xml",
    "xpi": "application/x-xpinstall",
    "xpm": "image/x-xpixmap",
    "xps": "application/vnd.ms-xpsdocument",  # XML Paper Specification
    "xsl": "text/xml",
    "xwd": "image/x-xwindowdump",
    "xyz": "chemical/x-pdb",
    "yaml": "text/x-yaml",
    "yml": "text/x-yaml",
    "zip": "application/zip",
}

def get_mime_type(file):
    return MIME_TYPES.get(file.extension, "text/plain")
