"""Alias for JDK tools"""

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = [
        "//visibility:public",
    ],
)

alias(
    name = "jdk-sts",
    actual = "@bazel_tools//tools/jdk:jdk",  # TODO(jiayanl) need to find a proper alterntaive than sts
    visibility = ["//visibility:public"],
)
