"""Alias for android sdk tools"""

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = [
        "//visibility:public",
    ],
)

alias(
    name = "adb",
    actual = "@androidsdk//:platform-tools/adb",
)

alias(
    name = "dexdump",
    actual = "@androidsdk//:dexdump",
    visibility = ["//visibility:public"],
)
