package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resource_files",
    srcs = glob(["res/**"]),
)

exports_files([
    "AndroidManifest.xml",
    "SampleAndroidManifest.xml",
    "SampleTest.java",
    "SampleActivity.java",
])
